# permissions for end users to view nodelabelers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodelabeler-viewer-role
rules:
- apiGroups:
  - kubebuilder.kube.node.labeler.io
  resources:
  - nodelabelers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubebuilder.kube.node.labeler.io
  resources:
  - nodelabelers/status
  verbs:
  - get
