# permissions for end users to edit nodelabelers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodelabeler-editor-role
rules:
- apiGroups:
  - kubebuilder.kube.node.labeler.io
  resources:
  - nodelabelers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebuilder.kube.node.labeler.io
  resources:
  - nodelabelers/status
  verbs:
  - get
