apiVersion: kubebuilder.kube.node.labeler.io/v1alpha1
kind: NodeLabeler
metadata:
  name: nodelabeler-sample
spec:
  nodeSelectorTerms:
  - matchExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values:
      - minikube
    - key: beta.kubernetes.io/os
      operator: In
      values:
      - linux
  - matchExpressions:
    - key: another-node-label-key
      operator: Exists
  # overwrite:
  #   labels:
  #     custom-label: "override-true"
  merge:
    labels:
      custom-label: "true"
    annotations:
      node-labeler-operator: works
    taints:
    - key: dedicated
      value: foo
      effect: PreferNoSchedule
