apiVersion: kubebuilder.kube.node.labeler.io/v1alpha1
kind: NodeLabeler
metadata:
  annotations:
    annotation1: value1
  generation: 1
  labels:
    type: unit-test
  name: simple-node-labeler
  namespace: default
spec:
  # merge:
  #   annotations:
  #     merge-annotation: "false"
  #   labels:
  #     merge-label: "false"
  #     test-label: "false"
  #   taints:
  #   - effect: NoExecute
  #     key: key1
  #     value: value1
  #   - effect: NoSchedule
  #     key: key2
  #     value: value2
  nodeSelectorTerms:
  - matchExpressions:
    - key: beta.kubernetes.io/arch
      operator: In
      values:
      - amd64
      - arch
  overwrite:
    # annotations:
    #   merge-annotation: "false"
    #   overwrite-annotation: "true"
    labels:
      not-found: "true"
      # merge-label: "false"
      # overwrite-label: "true"
    # taints:
    # - effect: PreferNoSchedule
    #   key: key1
    #   value: value1
